<a href="https://colab.research.google.com/github/AKJM567/PDE_CODE/blob/main/experiment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#creatimg a 1D array
array_1d = np.array([1,2,3,4,5])
print("1D Array:",array_1d)

#creating a 2D array
array_2d = np.array([[1,2,3],[4,5,6]])
print("2d Array:\n",array_2d)

1D Array: [1 2 3 4 5]
2d Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#creating an array of zeros
zeros = np.zeros((2,3))
print()

#creating an array of ones
ones = np.ones((2,3))
print("Array of ones:\n",ones)

#creating an array with a range of values
range_array = np.arange(10) # Changed 'arrange' to 'arange'
print("Range Array:", range_array)

#creating an array with evenly spaced values
linspace_array = np.linspace(0,1,5)
print("linspace array:",linspace_array)


Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 1 2 3 4 5 6 7 8 9]
linspace array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Element-wise addition
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)

#Element-wise substraction
print("substraction:",a-b) #Fixed: Removed the unexpected indentation

#Element-wise multiplication
print("multiplication:",a*b) #Fixed: Corrected the syntax error by adding quotes around "multiplication:"

#Element-wise division
print("division:",a/b) #Fixed: Added code for element-wise division and formatted the output

Addition: [5 7 9]
substraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [ ]:
import sympy as sp

In [ ]:
#define symbols
x,y = sp.symbols('x,y')

#define an expression
expr=x**2 + 2*x + 1

#simplify the expression
simplified_expr = sp.simplify(expr)
print(f"simplified  expression:{simplified_expr}")

